version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
      - .env.default
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/hello?user=hello&password=hello
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=hello

volumes:
  db_data:
